version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV_FILE=.env.production
    image: videopix-app
    container_name: videopix-app
    restart: unless-stopped
    networks:
      - videopix
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.36
    container_name: videopix-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - videopix
    # ❗ Porta 3306 não exposta (por segurança)

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql
    networks:
      - videopix

  nginx:
    image: nginx:1.25.3
    container_name: videopix-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - videopix

volumes:
  mysql-data:

networks:
  videopix:
    driver: bridge
