version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV_FILE=.env.production
    image: videopix-app
    container_name: videopix-app
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - videopix
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: videopix-mysql
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: videopix
      MYSQL_USER: videopix
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    networks:
      - videopix

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - videopix

  nginx:
    image: nginx:stable
    container_name: videopix-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - videopix

volumes:
  mysql-data:

networks:
  videopix:
    driver: bridge
