name: Deploy Videopix

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy para VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar PNPM e buildar projeto
        run: |
          echo "👉 Preparando o .env para o build do frontend"
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

          npm install -g pnpm
          pnpm install
          pnpm build

      - name: Configura chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Copiar build para VPS
        run: |
          scp -r public/build ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~/sites/videopix/public/

      - name: Deploy na VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e
            cd ~/sites/videopix

            echo "👉 Limpando imagens antigas..."
            docker rmi -f videopix-app nginx:1.25.3 || true

            echo "👉 Atualizando código..."
            git pull origin main

            echo "👉 Garantindo .env atualizado..."
            echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

            echo "👉 Subindo containers atualizados..."
            docker-compose down
            docker-compose up -d --build
          EOF
